---
title: "Pre Post Analysis"
author: "Max Bi"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nlme)
library(kableExtra)
# source("primary_obj_data.R")
# source("secondary_obj_data.R")
```

```{r}
KOH1 = as.Date("2023-04-05")
o1_bp = read_csv("Analysis Data/Obj1BPPrePost.csv")
names(o1_bp)[1] = "row_id"
o1_a1c = read_csv("Analysis Data/Obj1A1cPrePost.csv")
names(o1_a1c)[1] = "row_id"
o2_bp = read_csv("Analysis Data/Obj2BPPrePost.csv")
names(o2_bp)[1] = "row_id"
o2_a1c = read_csv("Analysis Data/Obj2A1cPrePost.csv")
names(o2_a1c)[1] = "row_id"
DAYS_IN_MONTH = 30.4
```

```{r}
# attendees
#   measured before 1st KOH visit: change date to 1st KOH visit
#   measured after 1st KOH visit: keep date
# non-attendees
#   measured before KOH 1: change date to KOH 1
#   measured after KOH 1: DNE
std_times = o1_bp %>% 
  group_by(UniqueIdentifier) %>% 
  summarize(
    pre_Date = min(BPDate),
    post_Date = max(BPDate),
    std_time = ifelse(BPDate == pre_Date, 0, ifelse(
      KOH == 0,
      as.numeric(post_Date - KOH1),
      ifelse(pre_Date < KOH1, as.numeric(post_Date - KOH1), as.numeric(post_Date - KOHDate))
    ))
  ) %>% 
  select(std_time) %>% 
  ungroup() %>% 
  mutate(
    row_id = as.numeric(o1_bp[["row_id"]]),
    std_months = std_time / DAYS_IN_MONTH
  ) %>% 
  select(std_time, row_id)

o1_bp = left_join(o1_bp, std_times, by="row_id") 
o1_bp = o1_bp %>% mutate(
  Sex = ifelse(o1_bp$Sex == "M", 1, 0),
  koh_cat = case_when(
    KOH.none == 1 ~ "None",
    KOH.one == 1 ~ "One",
    KOH.mult == 1 ~ "Multiple"
  )
)

std_times = o1_a1c %>% 
  group_by(UniqueIdentifier) %>% 
  summarize(
    pre_Date = min(A1cDate),
    post_Date = max(A1cDate),
    std_time = ifelse(A1cDate == pre_Date, 0, ifelse(
      KOH == 0,
      as.numeric(post_Date - KOH1),
      ifelse(pre_Date < KOH1, as.numeric(post_Date - KOH1), as.numeric(post_Date - KOHDate))
    ))
  ) %>% 
  select(std_time) %>% 
  ungroup() %>% 
  mutate(
    row_id = as.numeric(o1_a1c[["row_id"]]),
    std_months = std_time / DAYS_IN_MONTH
  ) %>% 
  select(std_time, row_id)

o1_a1c = left_join(o1_a1c, std_times, by="row_id") 
o1_a1c = o1_a1c %>% mutate(
  Sex = ifelse(o1_a1c$Sex == "M", 1, 0),
  koh_cat = case_when(
    KOH.none == 1 ~ "None",
    KOH.one == 1 ~ "One",
    KOH.mult == 1 ~ "Multiple"
  )
)
```

```{r}
o1_bp_ids = o1_bp$UniqueIdentifier %>% unique() %>% sample(0.5 * 0.25 * nrow(o1_bp))
o1_bp_pdt = o1_bp %>% filter(UniqueIdentifier %in% o1_bp_ids)
ggplot(data=o1_bp_pdt, mapping=aes(x=std_time, y=sys, group=UniqueIdentifier, color=koh_cat)) +
  geom_line() +
  geom_point() +
  labs(
    title="Spaghetti Plot of SBP Against Time",
    x="time since pre-measurement (days)",
    y="SBP (mm/Hg)"
  )

o1_a1c_ids = o1_a1c$UniqueIdentifier %>% unique() %>% sample(0.5 * 0.25 * nrow(o1_a1c))
o1_a1c_pdt = o1_a1c %>% filter(UniqueIdentifier %in% o1_a1c_ids)
ggplot(data=o1_a1c_pdt, mapping=aes(x=std_time, y=A1c, group=UniqueIdentifier, color=koh_cat)) +
  geom_line() +
  geom_point() +
  labs(
    title="Spaghetti Plot of A1c Against Time",
    x="time since pre-measurement (days)",
    y="A1c (percentage)"
  )
```


```{r}
mod_o1_bp = lme(
  fixed = sys ~ std_time * koh_cat + age + Sex + IncomeLevel + BLACERISK + avg.bmi,
  random = ~ std_time | UniqueIdentifier,
  data = o1_bp,
  method = "REML"
)
summary(mod_o1_bp)

mod_o1_a1c = lme(
  fixed = A1c ~ std_time * koh_cat + age + Sex + IncomeLevel + BLACERISK + avg.bmi,
  random = ~ std_time | UniqueIdentifier,
  data = o1_a1c,
  method = "REML"
)
summary(mod_o1_a1c)
```


```{r}
# measured before KOH 1: change date to KOH 1
# measured after KOH 1: keep date
std_times = o2_bp %>%
  group_by(UniqueIdentifier) %>%
  summarize(
    pre_Date = min(Date),
    post_Date = max(Date),
    std_time = ifelse(
      Date == pre_Date,
      0,
      # ifelse(pre_Date < KOH1, as.numeric(post_Date - KOH1), as.numeric(post_Date - pre_Date))
      as.numeric(post_Date - pre_Date)
    )
  ) %>%
  select(std_time) %>% 
  ungroup() %>%
  mutate(
    row_id = as.numeric(o2_bp[["row_id"]]),
    std_months = std_time / DAYS_IN_MONTH
  ) %>% 
  select(std_time, row_id)

o2_bp = left_join(o2_bp, std_times, by="row_id") 
o2_bp = o2_bp %>% mutate(Sex = ifelse(o2_bp$Sex == "M", 1, 0))

std_times = o2_a1c %>%
  group_by(UniqueIdentifier) %>%
  summarize(
    pre_Date = min(Date),
    post_Date = max(Date),
    std_time = ifelse(
      Date == pre_Date,
      0,
      # ifelse(pre_Date < KOH1, as.numeric(post_Date - KOH1), as.numeric(post_Date - pre_Date))
      as.numeric(post_Date - KOH1)
    )
  ) %>%
  select(std_time) %>% 
  ungroup() %>%
  mutate(
    row_id = as.numeric(o2_a1c[["row_id"]]),
    std_months = std_time / DAYS_IN_MONTH
  ) %>% 
  select(std_time, row_id)

o2_a1c = left_join(o2_a1c, std_times, by="row_id") 
o2_a1c = o2_a1c %>% mutate(Sex = ifelse(o2_a1c$Sex == "M", 1, 0))
```

```{r}
o2_bp_ids = o2_bp$UniqueIdentifier %>% unique() %>% sample(0.5 * 0.05 * nrow(o2_bp))
o2_bp_pdt = o2_bp %>% filter(UniqueIdentifier %in% o2_bp_ids) %>% mutate(Marsh = as.factor(Marsh))
ggplot(data=o2_bp_pdt, mapping=aes(x=std_time, y=Systolic, group=UniqueIdentifier, color=Marsh)) +
  geom_line() +
  geom_point() +
  labs(
    title="Spaghetti Plot of SBP Against Time",
    x="time since pre-measurement (days)",
    y="SBP (mm/Hg)"
  )

o2_a1c_ids = o2_a1c$UniqueIdentifier %>% unique() %>% sample(0.5 * 0.05 * nrow(o2_a1c))
o2_a1c_pdt = o2_a1c %>% filter(UniqueIdentifier %in% o2_a1c_ids) %>% mutate(Marsh = as.factor(Marsh))
ggplot(data=o2_a1c_pdt, mapping=aes(x=std_time, y=A1c, group=UniqueIdentifier, color=Marsh)) +
  geom_line() +
  geom_point() +
  labs(
    title="Spaghetti Plot of A1c Against Time",
    x="time since pre-measurement (days)",
    y="A1c (percentage)"
  )
```

```{r}
mod_o2_bp = lme(
  fixed = Systolic ~ std_time * Marsh + age + Sex + IncomeLevel + avg.bmi,
  random = ~ std_time | UniqueIdentifier,
  data = o2_bp,
  method = "REML"
)
summary(mod_o2_bp)

mod_o2_a1c = lme(
  fixed = A1c ~ std_time * Marsh + age + Sex + IncomeLevel + avg.bmi,
  random = ~ std_time | UniqueIdentifier,
  data = o2_a1c,
  method = "REML"
)
summary(mod_o2_a1c)
```

# Tables of Regression Results

```{r}
# format for regression results from models
coef_names = c("std_time:koh_catNone", "std_time:koh_catOne")
col_names = c("lower", "upper")

obj1_res = data.frame(
  rbind(
    cbind(intervals(mod_o1_a1c)$fixed[coef_names, col_names], summary(mod_o1_a1c)$tTable[coef_names, "p-value"]),
    cbind(intervals(mod_o1_bp, which="fixed")$fixed[coef_names, col_names], summary(mod_o1_bp)$tTable[coef_names, "p-value"])
  )
)

# obj1_res = data.frame(
#   est = c(summary(mod_o1_a1c)$tTable[coef_names, "Value"], summary(mod_o1_bp)$tTable[coef_names, "Value"]),
#   CI = intervals(mod_o1_a1c)$fixed[coef_names, col_names]
# )

rownames(obj1_res) = c("months:KOHnever", "months:KOHonce", "months:KOHnever ", "months:KOHonce ")
colnames(obj1_res)[4] = "p-value"

kable(obj1_res) %>% pack_rows("a1c_pre_post", 1, 2) %>% pack_rows("sbp_pre_post", 3, 4)
```

```{r}
# table for undajusted baseline results
o1_a1c_bltb = o1_a1c %>%
  group_by(UniqueIdentifier) %>% 
  summarize(
    pre_Date = min(A1cDate),
    A1c = ifelse(A1cDate == pre_Date, A1c, NA),
    koh_cat = koh_cat
  ) %>% 
  drop_na()

o1_bp_bltb = o1_bp %>%
  group_by(UniqueIdentifier) %>% 
  summarize(
    pre_Date = min(BPDate),
    sys = ifelse(BPDate == pre_Date, sys, NA),
    koh_cat = koh_cat
  ) %>% 
  drop_na()

o1_bltb = data.frame(
  KOHnever = c(mean((o1_a1c_bltb %>% filter(koh_cat == "None"))$A1c), mean((o1_bp_bltb %>% filter(koh_cat == "None"))$sys)),
    KOHonce = c(mean((o1_a1c_bltb %>% filter(koh_cat == "One"))$A1c), mean((o1_bp_bltb %>% filter(koh_cat == "One"))$sys)),
    KOHmultiple = c(mean((o1_a1c_bltb %>% filter(koh_cat == "Multiple"))$A1c), mean((o1_bp_bltb %>% filter(koh_cat == "Multiple"))$sys))
)

rownames(o1_bltb) = c("A1c", "SBP")

o1_bltb
```


\pagebreak

# Code Appendix

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```